// src/app/ui/ScoreSubmissionOverlay.tsx
import React from "react";
import { Modal } from "./Modal";
import { Button } from "./Button";

import { colors, spacing, typography, radius } from "@/theme/tokens";

export type SubmissionStep = "validating" | "signing" | "ready" | "error" | "skipped";

const stepMessages: Record<SubmissionStep, string> = {
  validating: "Validating score and preparing submission…",
  signing: "Requesting backend signature…",
  ready: "Approve in your wallet to finalize.",
  skipped: "Your previous high score is higher, so this run won't replace it.",
  error: "",
};

const stepTitles: Record<SubmissionStep, string> = {
  validating: "Validating your score",
  signing: "Securing your score",
  ready: "Ready to submit",
  skipped: "Personal best maintained",
  error: "Score submission failed",
};

const steps = ["validating", "signing", "ready"] as const;

type Props = {
  score: number;
  step: SubmissionStep;
  errorMessage?: string;
  onRetry?: () => void;
  onClose: () => void;
};

export function ScoreSubmissionOverlay(props: Props) {
  const currentIdx = steps.indexOf(props.step as (typeof steps)[number]);

  return (
    <Modal title={stepTitles[props.step]} onClose={props.onClose}>
      <div style={{ display: "flex", flexDirection: "column", gap: spacing.lg }}>
        <div style={{ textAlign: "center" }}>
          <div style={{ fontSize: typography.size["4xl"], fontWeight: typography.weight.bold, color: colors.text.primary }}>
            {props.score.toLocaleString()}
          </div>
          <div style={{ fontSize: typography.size.sm, color: colors.text.muted }}>pts</div>
        </div>

        {props.step !== "error" && (
          <p style={{ margin: 0, fontSize: typography.size.md, color: colors.text.secondary, textAlign: "center" }}>
            {stepMessages[props.step]}
          </p>
        )}

        {props.step === "error" && (
          <div style={{
            padding: spacing.lg,
            background: "rgba(239, 68, 68, 0.1)",
            border: `1px solid rgba(239, 68, 68, 0.3)`,
            borderRadius: radius.lg,
            color: colors.status.error,
            fontSize: typography.size.md,
            textAlign: "center",
          }}>
            {props.errorMessage ?? "An error occurred."}
          </div>
        )}

        {/* Progress Steps */}
        <div style={{ display: "flex", alignItems: "center", gap: spacing.xs, justifyContent: "center" }}>
          {steps.map((s, i) => (
            <React.Fragment key={s}>
              <div style={{
                display: "flex",
                alignItems: "center",
                gap: spacing.xs,
              }}>
                <div style={{
                  width: 24,
                  height: 24,
                  borderRadius: "50%",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  fontSize: typography.size.xs,
                  fontWeight: typography.weight.bold,
                  background: i < currentIdx ? colors.status.success : i === currentIdx ? colors.accent.primary : colors.border.default,
                  color: i <= currentIdx ? colors.text.primary : colors.text.muted,
                  transition: "all 0.3s ease",
                }}>
                  {i < currentIdx ? "✓" : i + 1}
                </div>
                <span style={{
                  fontSize: typography.size.xs,
                  color: i <= currentIdx ? colors.text.secondary : colors.text.muted,
                  textTransform: "capitalize",
                }}>
                  {s}
                </span>
              </div>
              {i < steps.length - 1 && (
                <div style={{
                  width: 24,
                  height: 2,
                  background: i < currentIdx ? colors.status.success : colors.border.subtle,
                  transition: "background 0.3s ease",
                }} />
              )}
            </React.Fragment>
          ))}
        </div>

        <div style={{ display: "flex", gap: spacing.sm }}>
          <Button variant="ghost" onClick={props.onClose} style={{ flex: 1 }}>
            Close
          </Button>
          {props.step === "error" && props.onRetry && (
            <Button onClick={props.onRetry} style={{ flex: 1 }}>
              Try again
            </Button>
          )}
        </div>
      </div>
    </Modal>
  );
}

// src/components/score-submission/score-submission-overlay.vue
<template>
  <section class="submission-overlay">
    <div class="submission-wrapper">
      <!-- Step 1: Validating Score -->
      <div v-if="step === 'validating'" class="submission-step">
        <div class="submission-spinner">
          <div class="spinner"></div>
        </div>
        <h2 class="submission-title">Validating Your Score</h2>
        <p class="submission-subtitle">{{ score }} points</p>
        <div class="submission-progress">
          <div class="progress-step active">
            <div class="step-dot"></div>
            <div class="step-label">Validating</div>
          </div>
          <div class="progress-step">
            <div class="step-dot"></div>
            <div class="step-label">Signing</div>
          </div>
          <div class="progress-step">
            <div class="step-dot"></div>
            <div class="step-label">Confirming</div>
          </div>
        </div>
      </div>

      <!-- Step 2: Signing Score -->
      <div v-else-if="step === 'signing'" class="submission-step">
        <div class="submission-spinner">
          <div class="spinner spin-faster"></div>
        </div>
        <h2 class="submission-title">Securing Your Score</h2>
        <p class="submission-subtitle">Generating secure signature...</p>
        <div class="submission-progress">
          <div class="progress-step active">
            <div class="step-dot"></div>
            <div class="step-label">Validating</div>
          </div>
          <div class="progress-step active">
            <div class="step-dot"></div>
            <div class="step-label">Signing</div>
          </div>
          <div class="progress-step">
            <div class="step-dot"></div>
            <div class="step-label">Confirming</div>
          </div>
        </div>
      </div>

      <!-- Step 3: Ready for Confirmation -->
      <div v-else-if="step === 'ready'" class="submission-step">
        <div class="submission-icon">
          <div class="icon-check">✓</div>
        </div>
        <h2 class="submission-title">Ready to Submit</h2>
        <p class="submission-subtitle">Approve in your wallet to finalize</p>
        <div class="submission-progress">
          <div class="progress-step active">
            <div class="step-dot"></div>
            <div class="step-label">Validating</div>
          </div>
          <div class="progress-step active">
            <div class="step-dot"></div>
            <div class="step-label">Signing</div>
          </div>
          <div class="progress-step pending">
            <div class="step-dot"></div>
            <div class="step-label">Confirming</div>
          </div>
        </div>
        <p class="submission-hint">👉 Check your wallet for confirmation request</p>
      </div>

      <!-- Error State -->
      <div v-else-if="step === 'error'" class="submission-step error">
        <div class="submission-icon error">
          <div class="icon-error">✕</div>
        </div>
        <h2 class="submission-title">Score Submission Failed</h2>
        <p class="submission-subtitle">{{ errorMessage }}</p>
        <button class="submission-btn retry" @click="$emit('retry')">Try Again</button>
      </div>
      
      <!-- Step: Skipped (Score Not Improved) -->
      <div v-else-if="step === 'skipped'" class="submission-step">
        <div class="submission-icon info">
          <div class="icon-info">★</div>
        </div>
        <h2 class="submission-title">Personal Best Maintained</h2>
        <p class="submission-subtitle">Your previous high score is higher!</p>
        <div class="submission-progress">
          <div class="progress-step active">
            <div class="step-dot"></div>
            <div class="step-label">Validating</div>
          </div>
          <div class="progress-step active">
            <div class="step-dot"></div>
            <div class="step-label">Skipped</div>
          </div>
          <div class="progress-step active">
            <div class="step-dot"></div>
            <div class="step-label">Done</div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script lang="ts">
export default {
  props: {
    score: { type: Number, required: true },
    step: { 
      type: String, 
      default: 'validating',
      validator: (v: string) => ['validating', 'signing', 'ready', 'error', 'skipped'].includes(v)
    },
    errorMessage: { type: String, default: 'An error occurred. Please try again.' },
  },
  emits: ['retry'],
};
</script>

<style lang="scss" scoped>
@import "@/styles/_variables";
@import "@/styles/_mixins";
@import "@/styles/_typography";

.submission-overlay {
  position: fixed;
  top: 0; left: 0; right: 0; bottom: 0;
  background: rgba(0, 0, 0, 0.85);
  z-index: 15;
  display: flex;
  align-items: center;
  justify-content: center;
  backdrop-filter: blur(2px);
}

.submission-wrapper {
  text-align: center;
}

.submission-step {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 24px;
  
  &.error {
    gap: 20px;
  }
}

.submission-spinner {
  width: 80px;
  height: 80px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.spinner {
  width: 100%;
  height: 100%;
  border: 3px solid rgba(0, 255, 136, 0.2);
  border-top-color: #00ff88;
  border-right-color: #00ff88;
  border-radius: 50%;
  animation: spin 1.5s linear infinite;
  
  &.spin-faster {
    animation: spin 0.8s linear infinite;
  }
}

@keyframes spin {
  to { transform: rotate(360deg); }
}

.submission-icon {
  width: 80px;
  height: 80px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 50%;
  background: rgba(0, 255, 136, 0.15);
  border: 2px solid rgba(0, 255, 136, 0.4);
  
  &.error {
    background: rgba(255, 100, 100, 0.15);
    border-color: rgba(255, 100, 100, 0.4);
  }
  
  &.info {
    background: rgba(255, 215, 0, 0.15);
    border-color: rgba(255, 215, 0, 0.4);
  }
}

.icon-check, .icon-error {
  font-size: 40px;
  font-weight: bold;
  color: #00ff88;
  animation: scaleIn 0.5s cubic-bezier(0.175, 0.885, 0.32, 1.275);
  
  &.error {
    color: #ff6464;
  }
}

.icon-info {
  font-size: 40px;
  font-weight: bold;
  color: #FFD700;
  animation: scaleIn 0.5s cubic-bezier(0.175, 0.885, 0.32, 1.275);
}

@keyframes scaleIn {
  0% {
    opacity: 0;
    transform: scale(0.5);
  }
  100% {
    opacity: 1;
    transform: scale(1);
  }
}

.submission-title {
  @include titleFont(28px);
  color: #FFF;
  margin: 0;
  letter-spacing: 0.5px;
}

.submission-subtitle {
  color: rgba(255, 255, 255, 0.7);
  font-size: 14px;
  margin: 0;
  line-height: 1.4;
}

.submission-progress {
  display: flex;
  gap: 12px;
  align-items: center;
  justify-content: center;
  margin: 8px 0;
}

.progress-step {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 6px;
  
  &.active .step-dot {
    background: #00ff88;
    box-shadow: 0 0 12px rgba(0, 255, 136, 0.6);
  }
  
  &.pending .step-dot {
    border-color: rgba(255, 255, 136, 0.5);
    animation: pulse-pending 1.5s ease-in-out infinite;
  }
}

@keyframes pulse-pending {
  0%, 100% {
    box-shadow: 0 0 0 0 rgba(255, 255, 136, 0.4);
  }
  50% {
    box-shadow: 0 0 0 6px rgba(255, 255, 136, 0.1);
  }
}

.step-dot {
  width: 10px;
  height: 10px;
  border-radius: 50%;
  border: 2px solid rgba(255, 255, 255, 0.3);
  transition: all 0.3s ease;
}

.step-label {
  font-size: 10px;
  color: rgba(255, 255, 255, 0.6);
  text-transform: uppercase;
  letter-spacing: 0.5px;
  transition: color 0.3s ease;
  
  .progress-step.active & {
    color: #00ff88;
  }
  
  .progress-step.pending & {
    color: rgba(255, 255, 136, 0.7);
  }
}

.submission-hint {
  color: rgba(255, 255, 136, 0.8);
  font-size: 13px;
  margin: 0;
  animation: fadeIn 0.6s ease-out 0.3s backwards;
}

@keyframes fadeIn {
  from {
    opacity: 0;
    transform: translateY(-4px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.submission-btn {
  padding: 10px 24px;
  background: rgba(255, 100, 100, 0.15);
  border: 1px solid rgba(255, 100, 100, 0.4);
  color: #ff6464;
  border-radius: 6px;
  cursor: pointer;
  font-size: 13px;
  font-weight: 500;
  transition: all 0.2s ease;
  
  &:hover {
    background: rgba(255, 100, 100, 0.25);
    border-color: rgba(255, 100, 100, 0.6);
    transform: translateY(-1px);
  }
  
  &:active {
    transform: translateY(0);
  }
}
</style>
